feat: CPS-423 Add tenant scope custom role to onboarding script (#29)
* chore: CPS-423 Add flowchart

* impr: CPS-423 Add tenant custom role

* impr: CPS-423 Add diff chart for PR review

* impr: CPS-423 Fix script

* docs: CPS-423 Update README.md

* impr: CPS-423 Address PR comments

# TODO update flow chart

* fix: CPS-423 Fix query bug

* docs: CPS-423 Update flow chart

* impr: CPS-423 Address flow, update graphs

* impr: CPS-423 Use scope parameter over subscription parameter

diff --git a/apply-roles b/apply-roles
--- a/apply-roles
+++ b/apply-roles
@@ -8,6 +8,7 @@ set -e
 readonly DEFAULT_APP_REGISTRATION_NAME="Conformity Azure access"
 readonly APPLICATION_KEY_NAME="Conformity Key"
 readonly CUSTOM_ROLE_NAME="Custom Role - Cloud One Conformity"
+readonly TENANT_CUSTOM_ROLE_NAME="Custom Role - Cloud One Conformity (Tenant scope)"
 
 option_error_and_exit() {
   echo "Error: Answer doesn't match any option."
@@ -95,6 +96,11 @@ check_for_custom_role_availability() {
   custom_role_definition_id=$(az role definition list --name "${CUSTOM_ROLE_NAME}" --query "[0].name" --output tsv)
 }
 
+check_for_tenant_custom_role_availability() {
+  echo " - Checking if tenant scope custom role definition has been created..."
+  tenant_custom_role_definition_id=$(az role definition list --name "${TENANT_CUSTOM_ROLE_NAME}" --query "[0].name" --output tsv)
+}
+
 generate_custom_role_definition() {
   local subscription_ids_in_active_directory=("$@")
   local assignable_scopes
@@ -109,7 +115,7 @@ generate_custom_role_definition() {
 
   echo "{ \
       \"Name\": \"${CUSTOM_ROLE_NAME}\", \
-      \"Description\": \"Subscription level custom role for Cloud Conformity access.\", \
+      \"Description\": \"Subscription level custom role for Cloud One Conformity access.\", \
       \"Actions\": [ \
           \"Microsoft.AppConfiguration/configurationStores/ListKeyValue/action\", \
           \"Microsoft.Network/networkWatchers/queryFlowLogStatus/action\", \
@@ -119,6 +125,21 @@ generate_custom_role_definition() {
       \"DataActions\": [], \
       \"NotDataActions\": [], \
       \"AssignableScopes\": [${assignable_scopes}] \
+    }"
+}
+
+generate_tenant_custom_role_definition() {
+  local tenant_id="${1}"
+
+  echo "{ \
+      \"Name\": \"${TENANT_CUSTOM_ROLE_NAME}\", \
+      \"Description\": \"Tenant level custom role for Cloud One Conformity access.\", \
+      \"Actions\": [ \
+          \"Microsoft.Management/managementGroups/read\" \
+      ], \
+      \"DataActions\": [], \
+      \"NotDataActions\": [], \
+      \"AssignableScopes\": [\"/providers/Microsoft.Management/managementGroups/${tenant_id}\"] \
     }"
 }
 
@@ -149,6 +170,33 @@ create_custom_role() {
   echo " - Custom role definition created (${custom_role_definition_id})"
 }
 
+create_tenant_custom_role() {
+  local tenant_id="${1}"
+  local attempts_to_retrieve_role=0
+  local role_definition
+
+  echo " - Creating tenant scope custom role definition..."
+
+  role_definition=$(generate_tenant_custom_role_definition "${tenant_id}")
+
+  az role definition create \
+    --role-definition "${role_definition}" >/dev/null
+
+  # It can take a bit of time for the role to be available to use so query until it is available
+  while [[ -z "${tenant_custom_role_definition_id}" ]] && [[ attempts_to_retrieve_role -lt 8 ]]; do
+    sleep 5
+    attempts_to_retrieve_role=$((attempts_to_retrieve_role + 1))
+    check_for_tenant_custom_role_availability
+  done
+
+  if [[ -z "${tenant_custom_role_definition_id}" ]] || [[ "${tenant_custom_role_definition_id}" == "null" ]]; then
+    echo "Error: Tenant scope Custom role creation failed"
+    exit 1
+  fi
+
+  echo " - Tenant scope Custom role definition created (${tenant_custom_role_definition_id})"
+}
+
 update_custom_role() {
   local subscription_ids_in_active_directory=("$@")
   local attempts_to_retrieve_role=0
@@ -170,9 +218,9 @@ apply_roles_to_subscription() {
   local is_custom_role_assigned
   local is_reader_role_assigned
 
-  echo "- Subscription: ${subscription_id}"
+  echo " - Subscription: ${subscription_id}"
 
-  echo "  - Checking custom role assignment..."
+  echo "   - Checking custom role assignment..."
 
   is_custom_role_assigned=$(az role assignment list \
     --role "${custom_role_definition_id}" \
@@ -182,17 +230,17 @@ apply_roles_to_subscription() {
     --output tsv)
 
   if [[ -z "${is_custom_role_assigned}" ]] || [[ "${is_custom_role_assigned}" == "null" ]]; then
-    echo "  - Assigning custom role..."
+    echo "   - Assigning custom role..."
 
     az role assignment create \
       --role "${custom_role_definition_id}" \
       --assignee "${service_principal_id}" \
-      --subscription "${subscription_id}" >/dev/null
+      --scope "/subscriptions/${subscription_id}" >/dev/null
   fi
 
-  echo "  - Custom role assigned"
+  echo "   - Custom role assigned"
 
-  echo "  - Checking built-in \"Reader\" role assignment..."
+  echo "   - Checking built-in \"Reader\" role assignment..."
 
   # retrieve built-in "Reader" role
   reader_role_id=$(az role definition list --name Reader --query "[0].name" --output tsv)
@@ -206,14 +254,42 @@ apply_roles_to_subscription() {
     --output tsv)
 
   if [[ -z "${is_reader_role_assigned}" ]] || [[ "${is_reader_role_assigned}" == "null" ]]; then
-    echo "  - Assigning built-in \"Reader\" role..."
+    echo "   - Assigning built-in \"Reader\" role..."
     az role assignment create \
       --role Reader \
       --assignee "${service_principal_id}" \
-      --subscription "${subscription_id}" >/dev/null
+      --scope "/subscriptions/${subscription_id}" >/dev/null
   fi
 
-  echo "  - \"Reader\" role assigned"
+  echo "   - \"Reader\" role assigned"
+}
+
+apply_tenant_custom_role_to_service_principal() {
+  local tenant_id="${1}"
+  local service_principal_id="${2}"
+  local is_tenant_custom_role_assigned
+
+  echo " - Tenant: ${tenant_id}"
+
+  echo "   - Checking tenant scope custom role assignment..."
+
+  is_tenant_custom_role_assigned=$(az role assignment list \
+    --role "${TENANT_CUSTOM_ROLE_NAME}" \
+    --scope "/providers/Microsoft.Management/managementGroups/${tenant_id}" \
+    --assignee "${service_principal_id}" \
+    --query "[0].id" \
+    --output tsv)
+
+  if [[ -z "${is_tenant_custom_role_assigned}" ]] || [[ "${is_tenant_custom_role_assigned}" == "null" ]]; then
+    echo "   - Assigning tenant scope custom role..."
+
+    az role assignment create \
+      --role "${tenant_custom_role_definition_id}" \
+      --assignee "${service_principal_id}" \
+      --scope "/providers/Microsoft.Management/managementGroups/${tenant_id}" >/dev/null
+  fi
+
+  echo "   - Tenant scope Custom role assigned"
 }
 
 main() {
@@ -223,9 +299,13 @@ main() {
   local service_principal_id
   local CREATE_APP
   local UPDATE_ROLE
+  local APPLY_ROLE
+  local UPSERT_TENANT_ROLE
 
-  UPDATE_ROLE='false'
   CREATE_APP='false'
+  UPDATE_ROLE='false'
+  APPLY_ROLE='false'
+  UPSERT_TENANT_ROLE='false'
 
   echo "This script will create the necessary resources for Cloud One Conformity to scan your Azure subscriptions."
 
@@ -268,7 +348,7 @@ main() {
       UPDATE_ROLE='true'
       ;;
     [nN] | [nN][oO])
-      echo "Custom role \"${CUSTOM_ROLE_NAME}\" will not be applied to new subscriptions."
+      echo "Custom role \"${CUSTOM_ROLE_NAME}\" will not have assignable scopes extended to new subscriptions."
       ;;
     *)
       option_error_and_exit
@@ -279,27 +359,56 @@ main() {
   readonly UPDATE_ROLE
 
   if [[ "${UPDATE_ROLE}" == 'false' ]]; then
-    read -rp "Would you like to apply \"${CUSTOM_ROLE_NAME}\" to a all subscriptions [Y|N]? " answer
+    read -rp "Would you like to apply \"${CUSTOM_ROLE_NAME}\" to subscriptions [Y|N]? " answer
     case "${answer}" in
     [yY] | [yY][eE][sS])
-      echo "\"${CUSTOM_ROLE_NAME}\" will be applied to all subscriptions."
+      APPLY_ROLE='true'
+      read -rp "Would you like to apply \"${CUSTOM_ROLE_NAME}\" to all subscriptions [Y|N]? " answer
+      case "${answer}" in
+      [yY] | [yY][eE][sS])
+        echo "\"${CUSTOM_ROLE_NAME}\" will be applied to all subscriptions."
+        ;;
+      [nN] | [nN][oO])
+        while true; do
+          read -rp "Please type in the subscription id: " subscription_id
+          subscription_name=$(az account list --query "[? id == '$subscription_id'].name" --output tsv)
+          if [[ -n "${subscription_name}" ]]; then
+            echo "Subscription \"${subscription_name}\" found."
+            break
+          fi
+          echo "Subscription wasn't found. Please type in the correct subscription id."
+        done
+        ;;
+      *)
+        option_error_and_exit
+        ;;
+      esac
       ;;
     [nN] | [nN][oO])
-      while true; do
-        read -rp "Please type in the subscription id: " subscription_id
-        subscription_name=$(az account list --query "[? id == '$subscription_id'].name" --output tsv)
-        if [[ -n "${subscription_name}" ]]; then
-          echo "Subscription \"${subscription_name}\" found."
-          break
-        fi
-        echo "Subscription wasn't found. Please type in the correct subscription id."
-      done
+      echo "\"${CUSTOM_ROLE_NAME}\" will not be applied to subscriptions."
+      ;;
+    *)
+      option_error_and_exit
+      ;;
+    esac
+
+    read -rp "Would you like to apply \"${TENANT_CUSTOM_ROLE_NAME}\" to tenant scope [Y|N]? " answer
+    case "${answer}" in
+    [yY] | [yY][eE][sS])
+      UPSERT_TENANT_ROLE='true'
+      echo "\"${TENANT_CUSTOM_ROLE_NAME}\" will be applied to the root tenant."
+      ;;
+    [nN] | [nN][oO])
+      echo "\"${TENANT_CUSTOM_ROLE_NAME}\" will not be applied to the root tenant."
       ;;
     *)
       option_error_and_exit
       ;;
     esac
   fi
+
+  readonly APPLY_ROLE
+  readonly UPSERT_TENANT_ROLE
 
   # retrieving Tenant id for Active Directory
   tenant_id=$(az ad sp show --id "${application_id}" --query "appOwnerOrganizationId" --output tsv)
@@ -315,38 +424,40 @@ main() {
     subscription_ids_in_active_directory+=("$line")
   done < <(az account list --query "[?tenantId=='${tenant_id}'].id" --output tsv)
 
-  echo "Configuring custom \"${CUSTOM_ROLE_NAME}\" role definition:"
+  if [[ "${UPDATE_ROLE}" == 'true' ]] || [[ "${APPLY_ROLE}" == 'true' ]]; then
+    echo "Configuring custom \"${CUSTOM_ROLE_NAME}\" role definition:"
 
-  # This will set a global variable if the custom role has been created
-  check_for_custom_role_availability
+    # This will set a global variable if the custom role has been created
+    check_for_custom_role_availability
 
-  if [[ "${UPDATE_ROLE}" == 'true' ]]; then
-    if [[ -z "${custom_role_definition_id}" ]] || [[ "${custom_role_definition_id}" == "null" ]]; then
-      echo "Error: Failed to update role as custom role definition not found"
+    if [[ "${UPDATE_ROLE}" == 'true' ]]; then
+      if [[ -z "${custom_role_definition_id}" ]] || [[ "${custom_role_definition_id}" == "null" ]]; then
+        echo "Error: Failed to update role as custom role definition not found"
+        exit 0
+      fi
+
+      update_custom_role "${subscription_ids_in_active_directory[@]}"
+      echo "It may take the Azure system a few minutes to reflect the changes"
+      echo "Please wait a few minutes before attempting to apply the updated role to any new subscriptions"
       exit 0
     fi
 
-    update_custom_role "${subscription_ids_in_active_directory[@]}"
-    echo "It may take the Azure system a few minutes to reflect the changes"
-    echo "Please wait a few minutes before attempting to apply the updated role to any new subscriptions"
-    exit 0
-  fi
-
-  if [[ -z "${custom_role_definition_id}" ]] || [[ "${custom_role_definition_id}" == "null" ]]; then
-    echo " - Custom role definition not found"
-    create_custom_role "${subscription_ids_in_active_directory[@]}"
-  else
-    echo " - Existing custom role definition found (${custom_role_definition_id})"
+    if [[ -z "${custom_role_definition_id}" ]] || [[ "${custom_role_definition_id}" == "null" ]]; then
+      echo " - Custom role definition not found"
+      create_custom_role "${subscription_ids_in_active_directory[@]}"
+    else
+      echo " - Existing custom role definition found (${custom_role_definition_id})"
+    fi
   fi
 
   # retrieve Service principal id
   service_principal_id=$(az ad sp show --id "${application_id}" --query "id" --output tsv)
 
-  if [[ -n "${subscription_id}" ]]; then
+  if [[ "${APPLY_ROLE}" == 'true' ]] && [[ -n "${subscription_id}" ]]; then
     echo "Assigning roles to subscription:"
     # A subscription id was passed in so only apply to that subscription
     apply_roles_to_subscription "${subscription_id}" "${service_principal_id}"
-  else
+  elif [[ "${APPLY_ROLE}" == 'true' ]]; then
     # Apply to all subscriptions in Active Directory
     echo "Assigning roles to ${#subscription_ids_in_active_directory[@]} subscriptions:"
     for subscription in "${subscription_ids_in_active_directory[@]}"; do
@@ -354,12 +465,33 @@ main() {
     done
   fi
 
+  if [[ "${UPSERT_TENANT_ROLE}" == 'true' ]]; then
+    echo "Configuring custom \"${TENANT_CUSTOM_ROLE_NAME}\" role definition:"
+
+    # This will set a global variable if the tenant custom role has been created
+    check_for_tenant_custom_role_availability
+
+    if [[ -z "${tenant_custom_role_definition_id}" ]] || [[ "${tenant_custom_role_definition_id}" == "null" ]]; then
+      echo " - Tenant scope Custom role definition not found"
+      create_tenant_custom_role "${tenant_id}"
+    else
+      echo " - Existing Tenant scope Custom role definition found (${tenant_custom_role_definition_id})"
+    fi
+
+    # Assing tenant scope custom role to service principal id
+    echo "Assigning role to tenant:"
+    apply_tenant_custom_role_to_service_principal "${tenant_id}" "${service_principal_id}"
+  fi
+
   # display information about the newly created App Registration
   echo "Finished."
   echo " - Active Directory Tenant id: ${tenant_id}"
   echo " - App Registration name: ${application_display_name}"
   echo " - Application id: ${application_id}"
-  echo " - Custom role name: ${CUSTOM_ROLE_NAME}"
+  echo " - Custom role name (Subscription scope): ${CUSTOM_ROLE_NAME}"
+  if [[ "${UPSERT_TENANT_ROLE}" == 'true' ]]; then
+    echo " - Custom role name (Tenant scope): ${TENANT_CUSTOM_ROLE_NAME}"
+  fi
 
   if [[ "${CREATE_APP}" == 'true' ]]; then
     echo " - Application Secret key: ${application_key_value}"
